#!/bin/bash

# Essential base packages list
basePackages=(
  base-devel
  git
  wget
  curl
  neovim
  nano
  archlinux-keyring
  reflector
  sudo
  openssh
  rsync
  nano
  linux-firmware
  amd-ucode
  mesa
  gvfs
)

# Prompt the user for a country/region, with a default value of "India"
read -r -p "Enter your country or region for the mirrorlist (default: India): " country

# If no input is provided, default to "India"
country=${country:-India}

# Function to check if Chaotic-AUR is already installed
is_chaotic_aur_installed() {
  grep -q "\[chaotic-aur\]" /etc/pacman.conf
}

# Function to install Chaotic-AUR if it's not installed
install_chaotic_aur() {
  # Add the Chaotic-AUR keyring and repository
  sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
  sudo pacman-key --lsign-key 3056513887B78AEB
  sudo pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'

  #Backup the pacman.conf file before proceeding
  sudo cp /etc/pacman.conf /etc/pacman.conf.bak

  # Add Chaotic-AUR repository to pacman.conf
  sudo tee -a /etc/pacman.conf >/dev/null <<EOL

[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOL

  # Synchronize package databases
  echo -e "${BLUE}Synchronizing package databases...${RESET}"
  logger "[INFO]:[Chaotic-AUR] Synchronizing package databases..."
  if sudo pacman -Syyu && sudo pacman -Fy; then
    echo -e "${GREEN}Chaotic-AUR repository added successfully.${RESET}"
    logger "[SUCCESS]:[Chaotic-AUR] Chaotic-AUR repository added successfully."
  else
    echo -e "${RED}Failed to synchronize package databases.${RESET}"
    logger "[FAILED]:[Chaotic-AUR] Failed to synchronize package databases."
    exit 1
  fi
}

# Main setup function to configure the base system
setup_base() {
  echo -e "${BLUE}Starting base system setup...${RESET}"
  logger "[INFO]:[BASE] Starting base system setup..."

  # Pacman spices
  if [ -f /etc/pacman.conf ] && [ ! -f /etc/pacman.conf.t2.bkp ]; then
    echo -e "${BLUE}Adding spices to pacman...${RESET}"
    sudo cp /etc/pacman.conf /etc/pacman.conf.t2.bkp

    sudo sed -i "/^#Color/c\Color\nILoveCandy
    /^#VerbosePkgLists/c\VerbosePkgLists
    /^#ParallelDownloads/c\ParallelDownloads = 5" /etc/pacman.conf
    sudo sed -i '/^#\[multilib\]/,+1 s/^#//' /etc/pacman.conf

  else
    echo -e "${YELLOW}Pacman was already configured...${RESET}"
  fi

  # Step 1: Install essential base packages
  echo -e "${BLUE}Installing base packages: ${basePackages[*]}...${RESET}"
  install_packages "${basePackages[@]}"

  # Check if the mirrorlist was generated by Reflector
  if grep -q "generated by Reflector" /etc/pacman.d/mirrorlist; then
    echo -e "${GREEN}Mirrorlist was already generated by Reflector. No update needed.${RESET}"
    logger "[INFO]:[Mirrorlist] Mirrorlist was already generated by Reflector. No update needed."
  else
    echo -e "${BLUE}Updating mirrorlist for ${country}...${RESET}"
    logger "[INFO]:[Mirrorlist] Updating mirrorlist for ${country}..."

    if sudo reflector --country "$country" --latest 5 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist; then
      echo -e "${GREEN}Mirrorlist updated successfully.${RESET}"
      logger "[SUCCESS]:[Mirrorlist] Mirrorlist updated successfully for the country ${country}."
    else
      echo -e "${RED}Failed to update mirrorlist.${RESET}"
      logger "[FAILED]:[Mirrorlist] Failed to update mirrorlist for the country ${country}."
    fi
  fi

  # Step 3: Add Chaotic-AUR repository
  echo -e "${BLUE}Checking for Chaotic-AUR repository...${RESET}"
  logger "[INFO]:[Chaotic-AUR] Checking for Chaotic-AUR repository..."

  if is_chaotic_aur_installed; then
    echo -e "${YELLOW}Chaotic-AUR repository is already installed.${RESET}"
    logger "[INFO]:[Chaotic-AUR] Chaotic-AUR repository is already installed." 
  else
    echo -e "${BLUE}Chaotic-AUR is not installed. Installing now...${RESET}"
    logger "[INFO]:[Chaotic-AUR] Chaotic-AUR is not installed. Installing now..."
    install_chaotic_aur
  fi
}

setup_base
